### ISSUE TITLE
No longer works for organizations

### ISSUE THREAD

**Issue by elifoster** [ghuls-apps/ghuls-web#12]
Because of the calendar stuff, it throws a NoMethodError `each` for `nilClass` when trying to get the profile data. A simple check for whether they are a user or an org would suffice.

Honestly, I think that we should use a separate view for organizations, because it's kind of weird and obvious to say "ghuls-apps hasn't contributed to any organizations :("

```
2016-02-17T18:31:52.542584+00:00 app[web.1]: 2016-02-17 18:31:52 - NoMethodError - undefined method `each' for nil:NilClass:
2016-02-17T18:31:52.542595+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
2016-02-17T18:31:52.542615+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
2016-02-17T18:31:52.542617+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
2016-02-17T18:31:52.542620+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
2016-02-17T18:31:52.542592+00:00 app[web.1]:    /app/main.rb:46:in `block in <top (required)>'
2016-02-17T18:31:52.542623+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
2016-02-17T18:31:52.542594+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
2016-02-17T18:31:52.542604+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
2016-02-17T18:31:52.542614+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
2016-02-17T18:31:52.542619+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
2016-02-17T18:31:52.542596+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
2016-02-17T18:31:52.542599+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
2016-02-17T18:31:52.542600+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
2016-02-17T18:31:52.542606+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
2016-02-17T18:31:52.542611+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
2016-02-17T18:31:52.542597+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
2016-02-17T18:31:52.542602+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
2016-02-17T18:31:52.542606+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
2016-02-17T18:31:52.542613+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
2016-02-17T18:31:52.542623+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
2016-02-17T18:31:52.542625+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
2016-02-17T18:31:52.542598+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
2016-02-17T18:31:52.542608+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
2016-02-17T18:31:52.542618+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
2016-02-17T18:31:52.542600+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
2016-02-17T18:31:52.542601+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
2016-02-17T18:31:52.542626+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
2016-02-17T18:31:52.542603+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
2016-02-17T18:31:52.542607+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
2016-02-17T18:31:52.542612+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
2016-02-17T18:31:52.542620+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
2016-02-17T18:31:52.542590+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/github-calendar-1.0.0/lib/github/calendar.rb:97:in `get_monthly'
2016-02-17T18:31:52.542604+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
2016-02-17T18:31:52.542609+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
2016-02-17T18:31:52.542622+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
2016-02-17T18:31:52.542624+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
2016-02-17T18:31:52.542626+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
2016-02-17T18:31:52.542628+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
2016-02-17T18:31:52.542634+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
2016-02-17T18:31:52.562720+00:00 app[web.1]: 76.115.175.15 - - [17/Feb/2016:18:31:52 +0000] "GET /analyze?user=esteemed-innovation HTTP/1.1" 500 30 5.2115
2016-02-17T18:31:52.542610+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
2016-02-17T18:31:52.542611+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
2016-02-17T18:31:52.542616+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2016-02-17T18:31:52.542616+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2016-02-17T18:31:52.542621+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
2016-02-17T18:31:52.542627+00:00 app[web.1]:    /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
```

**Comment by elifoster** [comment]
@Strikingwolf What do you think about a separate view for orgs?
