### ISSUE TITLE
Application Error for my GitHub Username

### ISSUE THREAD

**Issue by zeke** [ghuls-apps/ghuls-web#15]
Originally opened this at https://github.com/ghuls-apps/ghuls-deprecated/issues/30, but then realized that repo is deprecated)

http://ghuls.herokuapp.com/analyze?user=zeke spins for a while, then:

<img width="614" alt="screen shot 2016-03-06 at 9 34 00 am" src="https://cloud.githubusercontent.com/assets/2289/13555797/9886fbbe-e37e-11e5-816a-7da91dc23f5b.png">

Would love to see the results. Let me know how I can help.

ELI EDIT:
Relevant Logs:

```
2016-03-06T17:33:13.662376+00:00 app[web.1]: 2016-03-06 17:33:13 - NoMethodError - undefined method `each' for nil:NilClass:
2016-03-06T17:33:13.662386+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/github-calendar-1.0.0/lib/github/calendar.rb:97:in `get_monthly'
```

**Comment by elifoster** [comment]
Weird. It errored the first few times I tried using GitHub::Calendar#get_monthly('zeke') (in pry), but now it seems to be working fine, returning `{"01"=>226, "02"=>38, "03"=>800, "04"=>339, "05"=>77, "06"=>24, "07"=>37, "08"=>26, "09"=>69, "10"=>50, "11"=>120, "12"=>97}`. Still erroring on the webpage. I am really curious as to what is actually causing this issue. I'll open an issue over at the github-calendar-api repo.

**Comment by elifoster** [comment]
Hm, I restarted the dynos on Heroku and it seems to be working fine now.

**Comment by zeke** [comment]
Huh, different error for me this time:

<img width="472" alt="screen shot 2016-03-06 at 2 50 40 pm" src="https://cloud.githubusercontent.com/assets/2289/13557743/d8b77890-e3aa-11e5-99a5-5548b708c41a.png">

**Comment by elifoster** [comment]
That one appears to be just some random error thrown by Sinatra/Puma/Rack. Same error, but it doesn't reference the same code:
```
2016-03-06T22:52:45.279781+00:00 app[web.1]: 2016-03-06 22:52:45 - NoMethodError - undefined method `each' for nil:NilClass:
2016-03-06T22:52:45.279827+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
2016-03-06T22:52:45.279828+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
2016-03-06T22:52:45.279829+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
2016-03-06T22:52:45.279833+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
2016-03-06T22:52:45.279834+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
2016-03-06T22:52:45.279840+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2016-03-06T22:52:45.279846+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
2016-03-06T22:52:45.279820+00:00 app[web.1]: 	/app/main.rb:46:in `block in <top (required)>'
2016-03-06T22:52:45.279833+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
2016-03-06T22:52:45.279822+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
2016-03-06T22:52:45.279823+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
2016-03-06T22:52:45.279843+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
2016-03-06T22:52:45.279821+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
2016-03-06T22:52:45.279823+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
2016-03-06T22:52:45.279826+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
2016-03-06T22:52:45.279831+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
2016-03-06T22:52:45.279832+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
2016-03-06T22:52:45.279817+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/github-calendar-1.0.0/lib/github/calendar.rb:97:in `get_monthly'
2016-03-06T22:52:45.279836+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
2016-03-06T22:52:45.279837+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'

```

**Comment by elifoster** [comment]
That one appears to be the same error. I still have absolutely no idea why this is happening occasionally. Although, unlike before, this errored when I ran it on myself as well.

**Comment by elifoster** [comment]
This may have been fixed by 2bfb3a9, but I'm not sure as we are having some performance issues which prevent Heroku from loading anything.
